-- Sitema de Becas Correguido

-- Tabla Estudainte
CREATE TABLE ESTUDIANTE (
    ID_ESTUDAINTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL, 
    APELLIDO VARCHAR2(50) NOT NULL,
    DPI VARCHAR2(100) UNIQUE NOT NULL,
    CORRREO VARCHAR(100) UNIQUE NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    NIVEL_EDUCATIVO VARCHAR2(20) NOT NULL,
    /* Restricciones que se pueen aplicar dentro de la tabla 
    Se aplian en nombre, apellido y nivel educativo*/
    CONSTRAINT CK_EST_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
        
    CONSTRAINT CK_EST_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO, '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
        
    CONSTRAINT CK_EST_NIVEL
        CHECK (UPPER(NIVEL_EDUCATIVO) IN ('MEDIO','UNIVERSIDAD','POSGRADO'))
);

ALTER TABLE ESTUDIANTE
ADD CONSTRAINT CK_EST_DPI 
    CHECK (REGEXP_LIKE(DPI,'[0-9]{13}$'));

-- TABLA DOCENTE
CREATE TABLE DOCENTE (
    ID_DOCENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    NIVEL_EDUCACION VARCHAR2(20) NOT NULL,
 
    CONSTRAINT CK_DOC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_DOC_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_DOC_NIVEL
        CHECK (UPPER(NIVEL_EDUCACION) IN ('MEDIO', 'UNIVERSITARIO', 'POSGRADO'))
);

ALTER TABLE DOCENTE
ADD CONSTRAINT CK_DOC_CORREO
    CHECK(REGEXP_LIKE(CORREO,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'));
    
SELECT * FROM DOCENTE;

-- TABLA USUARIO 
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    /*Restricciones que pueden estar dentro de la tabla que es nombre*/ 
    CONSTRAINT CK_USU_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

/*Restricciones que se realizan dentro de un trigger*/
CREATE OR REPLACE TRIGGER trg_valida_pasword_usuario
BEFORE INSERT OR UPDATE OF Contrasena ON USUARIO
FOR EACH ROW
DECLARE
    v_Contrasena VARCHAR2(100);
BEGIN
    v_Contrasena := :NEW.Contrasena;

    IF LENGTH(v_Contrasena) < 8 OR LENGTH(v_Contrasena) > 18 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener entre 8 y 18 caracteres');
    END IF;

    IF NOT REGEXP_LIKE(v_Contrasena, '[A-Z]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos una letra mayuscula');
    END IF;

    IF NOT REGEXP_LIKE(v_Contrasena, '[a-z]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos una letra minuscula');
    END IF;

    IF NOT REGEXP_LIKE(v_Contrasena, '[0-9]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos un numero');
    END IF;

    IF NOT REGEXP_LIKE(v_Contrasena, '[^A-Za-z0-9]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos un caracter especial');
    END IF;
END;  

SELECT * FROM USUARIO;

-- Tabla Universidad
CREATE TABLE UNIVERSIDAD (
    ID_UNIVERSIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    /*Restricciones que pueden esatr dentro de la tabla en este caso es nombre*/ 
    CONSTRAINT CK_UNI_NOMBRE
        CHECK(REGEXP_LIKE(NOMBRE, '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

ALTER TABLE UNIVERSIDAD
ADD CONSTRAINT CK_UNI_DIRECCION
    CHECK (LENGTH(TRIM(DIRECCION)) >= 10);
    
SELECT * FROM UNIVERSIDAD;

-- Tabla escuela
CREATE TABLE ESCUELA (
    ID_ESCUELA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
 
    CONSTRAINT CK_ESC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
    
    CONSTRAINT CK_ESC_DIRECCION
        CHECK (LENGTH(TRIM(DIRECCION)) >= 10)
);

SELECT * FROM ESCUELA;

-- Tabla isntitución
CREATE TABLE INSTITUCION (
    ID_INSTITUCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UNIVERSIDAD NUMBER,
    ID_ESCUELA NUMBER,
 
    CONSTRAINT FK_INST_UNIVERSIDAD
        FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD(ID_UNIVERSIDAD),
 
    CONSTRAINT FK_INST_ESCUELA
        FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA),
 
    CONSTRAINT CK_INST_TIPO
        CHECK (
            (ID_UNIVERSIDAD IS NOT NULL AND ID_ESCUELA IS NULL)
            OR
            (ID_UNIVERSIDAD IS NULL AND ID_ESCUELA IS NOT NULL)
        )
);

SELECT * FROM INSTITUCION;

-- Tabla convocatoria
CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FINALIZACION DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    ID_INSTITUCION NUMBER,
 
    CONSTRAINT FK_CONV_INSTITUCION
        FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
 
    CONSTRAINT CK_CONV_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_CONV_FECHAS
        CHECK (FECHA_FINALIZACION >= FECHA_INICIO),
 
    CONSTRAINT CK_CONV_ESTADO
        CHECK (UPPER(ESTADO) IN ('ABIERTO', 'CERRADO', 'CANCELADO'))
);

SELECT * FROM CONVOCATORIA;

-- Tabla de solicitud de becas
DROP TABLE SOLICITUD_BECAS CASCADE CONSTRAINTS;

CREATE TABLE SOLICITUD_BECAS (
    ID_SOLICITUD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ESTUDAINTE NUMBER NOT NULL,
    ID_CONVOCATORIA NUMBER NOT NULL,
    ESTADO_SOLICITUD VARCHAR2(20) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,

    CONSTRAINT FK_SOL_ESTUDIANTE
        FOREIGN KEY (ID_ESTUDAINTE) REFERENCES ESTUDIANTE(ID_ESTUDAINTE),

    CONSTRAINT FK_SOL_CONVOCATORIA
        FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA(ID_CONVOCATORIA),

    CONSTRAINT CK_SOL_ESTADO
        CHECK (UPPER(ESTADO_SOLICITUD) IN ('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA')),

    CONSTRAINT UQ_SOL_EST_CONV
        UNIQUE (ID_ESTUDAINTE, ID_CONVOCATORIA)
);


/*Restricciones que se realiza con trigger*/
CREATE OR REPLACE TRIGGER trg_valida_estado_convocatoria_becas
BEFORE INSERT ON SOLICITUD_BECAS
FOR EACH ROW
DECLARE
    v_estado CONVOCATORIA.ESTADO%TYPE;
BEGIN
    SELECT estado
      INTO v_estado
      FROM CONVOCATORIA
     WHERE id_convocatoria = :NEW.id_convocatoria;

    IF UPPER(v_estado) IN ('CERRADO', 'CANCELADO') THEN
        RAISE_APPLICATION_ERROR(
            -20020,
            'No se puede ingresar la solicitud. La convocatoria está ' || v_estado || '.'
        );
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20021,
            'La convocatoria asociada (ID: ' || :NEW.id_convocatoria || ') no existe.'
        );
END;

SELECT * FROM SOLICITUD_BECAS;

-- Tabla Comite
CREATE TABLE COMITE (
    ID_COMITE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_COMITE VARCHAR2(50) NOT NULL,
    
    CONSTRAINT CK_COM_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE_COMITE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

SELECT * FROM COMITE;

-- Tabla miembros del comite
CREATE TABLE MIEMBRO_COMITE (
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    ES_EVALUADOR CHAR(1) DEFAULT 'N' NOT NULL,
    ESTADO_AUTORIZACION VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
 
    CONSTRAINT PK_MIEMBRO_COMITE
        PRIMARY KEY (ID_COMITE, ID_DOCENTE),
 
    CONSTRAINT FK_MIEMBRO_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),
 
    CONSTRAINT FK_MIEMBRO_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
 
    CONSTRAINT CK_MIEMBRO_ES_EVALUADOR
        CHECK (ES_EVALUADOR IN ('S','N')),
 
    CONSTRAINT CK_MIEMBRO_ESTADO_AUT
        CHECK (UPPER(ESTADO_AUTORIZACION) IN ('AUTORIZADO','ACTIVO','INACTIVO'))
);

/*Restricciones de la tabla miembros del comite que se hace por medio de un triger*/
CREATE OR REPLACE TRIGGER trg_valida_miembro_autorizado
BEFORE INSERT OR UPDATE ON MIEMBRO_COMITE
FOR EACH ROW
BEGIN
    IF UPPER(:NEW.estado_autorizacion) NOT IN ('AUTORIZADO', 'ACTIVO')
       OR :NEW.es_evaluador = 'N' THEN
 
        RAISE_APPLICATION_ERROR(
            -20030,
            'Acceso denegado: El docente (ID: ' || :NEW.id_docente || ') no está autorizado para realizar evaluaciones.'
        );
 
    END IF;
END;

SELECT * FROM MIEMBRO_COMITE;

-- Tabla Evaluación
CREATE TABLE EVALUACION (
    ID_EVALUACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    ID_SOLICITUD NUMBER NOT NULL,
    CALIFICACION NUMBER NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    RESULTADO VARCHAR2(20),
 
    CONSTRAINT FK_EVAL_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),
 
    CONSTRAINT FK_EVAL_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
 
    CONSTRAINT FK_EVAL_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
 
    CONSTRAINT UQ_EVAL_COMITE_DOC_SOL
        UNIQUE (ID_COMITE, ID_DOCENTE, ID_SOLICITUD),
        
    CONSTRAINT chk_rango_calificacion
        CHECK (calificacion BETWEEN 0 AND 100),
    
    CONSTRAINT CK_EVAL_ESTADO
    CHECK (UPPER(ESTADO) IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADA'))
);

/* Restricciones que se implementan por medio de un trigger para la tabla evaluacion*/
CREATE OR REPLACE TRIGGER trg_valida_evaluador_autorizado
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
DECLARE
    v_autorizado VARCHAR2(2);
BEGIN
    SELECT es_evaluador
      INTO v_autorizado
      FROM MIEMBRO_COMITE
     WHERE id_comite = :NEW.id_comite
       AND id_docente = :NEW.id_docente;
 
    IF v_autorizado <> 'S' THEN
        RAISE_APPLICATION_ERROR(
            -20031,
            'El miembro del comité seleccionado no tiene permisos de evaluador autorizado.'
        );
    END IF;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20032,
            'El docente especificado no pertenece a este comité.'
        );
END;

CREATE OR REPLACE TRIGGER trg_gestion_evaluacion_beca
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
BEGIN
    -- 1. Bloquear cambios si la evaluación ya estaba completada
    IF UPDATING AND UPPER(:OLD.estado) = 'COMPLETADA' THEN
        RAISE_APPLICATION_ERROR(
            -20050,
            'No se puede modificar una evaluación que ya ha sido finalizada.'
        );
    END IF;
 
    -- 2. Calcular el resultado (APROBADA/RECHAZADA) según la calificación ingresada
    IF :NEW.calificacion IS NOT NULL THEN
        IF :NEW.calificacion >= 70 THEN
            :NEW.resultado := 'APROBADA';
        ELSE
            :NEW.resultado := 'RECHAZADA';
        END IF;
    END IF;
END;

SELECT * FROM EVALUACION;

-- Tabla Documento

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    FORMATO VARCHAR2(50) NOT NULL,
    TAMANO NUMBER NOT NULL,
    ARCHIVO BLOB,
    ENLACE VARCHAR2(500),
    FECHA_CARGA DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_DOCENTE NUMBER,
 
    CONSTRAINT FK_DOC_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
 
    CONSTRAINT FK_DOC_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
 
    CONSTRAINT FK_DOC_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
        
    CONSTRAINT CK_DOC_TAMANO
        CHECK (TAMANO > 0 AND TAMANO <= 5242880)  -- 5 Megabytes
);
 
SELECT * FROM DOCUMENTO;

-- Tabla de historial de estado
CREATE TABLE HISTORIAL_ESTADO (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    FECHA_CAMBIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(50) NOT NULL,
    ESTADO_NUEVO VARCHAR2(50) NOT NULL,
 
    CONSTRAINT FK_HIST_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
        
    CONSTRAINT CK_HIST_ESTADO_ANT
        CHECK (UPPER(ESTADO_ANTERIOR) IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA')),
        
    CONSTRAINT CK_HIST_ESTADO_NUE
        CHECK (UPPER(ESTADO_NUEVO) IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA')),
    
    CONSTRAINT CK_HIST_ESTADO_DIF
        CHECK (UPPER(ESTADO_ANTERIOR) <> UPPER(ESTADO_NUEVO))
);
 
/*Restriccion de trigger para la tabla historial de estado que nos permite registrar cualuier cambio en el estado de una solicitud de beca*/
CREATE OR REPLACE TRIGGER TRG_AUDITA_ESTADO_SOLICITUD
AFTER UPDATE OF ESTADO_SOLICITUD ON SOLICITUD_BECAS
FOR EACH ROW
BEGIN
    IF :OLD.ESTADO_SOLICITUD <> :NEW.ESTADO_SOLICITUD THEN
        INSERT INTO HISTORIAL_ESTADO (
            ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO, FECHA_CAMBIO
        ) VALUES (
            :OLD.ID_SOLICITUD, :OLD.ESTADO_SOLICITUD, :NEW.ESTADO_SOLICITUD, SYSDATE
        );
    END IF;
END;

SELECT * FROM HISTORIAL_ESTADO;


-- -------------------------------------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------------------------------------
-- Datos de Prueba - Minimo 20 registos por tabla
-- -------------------------------------------------------------------------------------------------------------
-- -------------------------------------------------------------------------------------------------------------
-- Datos para la tabla Estudiante -- Parametros de acpetacion 'MEDIO','UNIVERSIDAD','POSGRADO'
-- 1
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Juan', 'Perez', '1000000000000', 'estudiante1@gmail.com', DATE '1998-01-01', 'MEDIO'); 
-- 2
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Pedro', 'Lopez', '1000000000001', 'estudiante2@gmail.com', DATE '1999-02-02', 'UNIVERSIDAD');
-- 3
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Maria', 'Garcia', '1000000000002', 'estudiante3@gmail.com', DATE '2000-03-03', 'POSGRADO');
-- 4
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Ana', 'Martinez', '1000000000003', 'estudiante4@gmail.com', DATE '2001-04-04', 'MEDIO');
-- 5
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Luis', 'Rodriguez', '1000000000004', 'estudiante5@gmail.com', DATE '2002-05-05', 'UNIVERSIDAD');
-- 6
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Carlos', 'Hernandez', '1000000000005', 'estudiante6@gmail.com', DATE '2003-06-06', 'POSGRADO');
--  7
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Sofia', 'Gonzalez', '1000000000006', 'estudiante7@gmail.com', DATE '2004-07-07', 'MEDIO');
--  8
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Elena', 'Ramirez', '1000000000007', 'estudiante8@gmail.com', DATE '2005-08-08', 'UNIVERSIDAD');
-- 9
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Diego', 'Torres', '1000000000008', 'estudiante9@gmail.com', DATE '1998-09-09', 'POSGRADO');
-- 10
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORRREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)  
VALUES ('Andrea', 'Flores', '1000000000009', 'estudiante10@gmail.com', DATE '1999-10-10', 'MEDIO');

SELECT * FROM ESTUDIANTE;

-- Datos para la tabla Docente -- Parametros de acpetacion 'MEDIO', 'UNIVERSITARIO', 'POSGRADO'
-- 1
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Ana', 'Hernandez', 'docente1@usac.edu.gt', 'MEDIO');
-- 2
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Luis', 'Gonzalez', 'docente2@usac.edu.gt', 'UNIVERSITARIO');
-- 3
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Carlos', 'Ramirez', 'docente3@usac.edu.gt', 'POSGRADO');
-- 4
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Sofia', 'Torres', 'docente4@usac.edu.gt', 'MEDIO');
-- 5
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Elena', 'Flores', 'docente5@usac.edu.gt', 'UNIVERSITARIO');
-- 6
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Diego', 'Diaz', 'docente6@usac.edu.gt', 'POSGRADO');
-- 7
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Andrea', 'Morales', 'docente7@usac.edu.gt', 'MEDIO');
-- 8
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Miguel', 'Castillo', 'docente8@usac.edu.gt', 'UNIVERSITARIO');
-- 9
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Laura', 'Ortiz', 'docente9@usac.edu.gt', 'POSGRADO');
-- 10
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION) 
VALUES ('Jorge', 'Chavez', 'docente10@usac.edu.gt', 'MEDIO');

SELECT * FROM DOCENTE;

-- Datos para la tabla Usuario
-- 1
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Diego', 'Clave02!', 'usuario2@sistema.com');
-- 2
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Andrea', 'Clave03!', 'usuario3@sistema.com');
-- 3
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Miguel', 'Clave04!', 'usuario4@sistema.com');
-- 
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Laura', 'Clave05!', 'usuario5@sistema.com');
-- 5
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Elena', 'Clave01!', 'usuario1@sistema.com');
-- 6
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Jorge', 'Clave06!', 'usuario6@sistema.com');
-- 7 
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Paola', 'Clave07!', 'usuario7@sistema.com');
-- 8 
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Fernando', 'Clave08!', 'usuario8@sistema.com');
-- 9
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Ricardo', 'Clave10!', 'usuario10@sistema.com');
-- 10
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO) 
VALUES ('Valeria', 'Clave11!', 'usuario11@sistema.com');

SELECT * FROM USUARIO;

-- Datos de Universidad
-- 1
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Central', 'Zona 10 Ciudad Guatemala');
-- 2
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad del Valle', 'Zona 15 Vista Hermosa');
-- 3
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad San Carlos', 'Zona 12 Ciudad Universitaria');
-- 4
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Rafael Landivar', 'Vista Hermosa III Zona 16');
-- 5
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Mariano Galvez', 'Zona 2 Ciudad Guatemala');
-- 6
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Panamericana', 'Zona 13 Aviacion');
-- 7
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Galileo', 'Zona 4 Torre Empresarial');
-- 8
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Francisco Marroquin', 'Zona 10 Las Margaritas');
-- 9
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad Rural', 'Zona 5 Colonia Roosevelt');
-- 10
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION) VALUES ('Universidad del Istmo', 'Zona 16 Km 12 Carretera');

SELECT * FROM UNIVERSIDAD;

-- Datos para Escuela 
-- 1
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Tecnica Nacional', 'Zona 1 Ciudad Guatemala');
-- 2
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Normal Central', 'Zona 3 Barrio San Antonio');
-- 3
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela de Comercio', 'Zona 9 Avenida Reforma');
-- 4
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Belga Guatemalteca', 'Zona 14 Colonia Oakland');
-- 5
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Adventista', 'Zona 11 Colonia Panorama');
-- 6
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Bilingue Internacional', 'Zona 15 Vista Hermosa II');
-- 7
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Integral Maya', 'Zona 7 Colonia Landivar');
-- 8
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Liceo Guatemala', 'Zona 6 Colonia Centroamerica');
-- 9
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Monte Maria', 'Zona 16 Camino Real');
-- 10
INSERT INTO ESCUELA (NOMBRE, DIRECCION) VALUES ('Escuela Interamericana', 'Zona 10 Avenida Las Americas');

SELECT * FROM ESCUELA;

-- Datos para INSTITUCION
-- 1
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (1, NULL);
-- 2
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (2, NULL);
-- 3
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (3, NULL);
-- 4
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (4, NULL);
-- 5
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (5, NULL);
-- 6
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (6, NULL);
-- 7
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (7, NULL);
-- 8
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (8, NULL);
-- 9
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (9, NULL);
-- 10
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (10, NULL);
-- 11
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 1);
-- 12
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 2);
-- 13
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 3);
-- 14
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 4);
-- 15
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 5);
-- 16
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 6);
-- 17
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 7);
-- 18
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 8);
-- 19
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 9);
-- 20
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA) VALUES (NULL, 10);

SELECT * FROM INSTITUCION;

-- Datos para convocatoria
-- 1
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Excelencia Academica', DATE '2025-01-01', DATE '2025-01-28', 'ABIERTO', 1);
-- 2
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Apoyo Estudiantil', DATE '2025-02-01', DATE '2025-02-28', 'ABIERTO', 2);
-- 3
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Merito Deportivo', DATE '2025-03-01', DATE '2025-03-28', 'ABIERTO', 3);
-- 4
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Investigacion Cientifica', DATE '2025-04-01', DATE '2025-04-28', 'ABIERTO', 4);
-- 5
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Emprendimiento Joven', DATE '2025-05-01', DATE '2025-05-28', 'ABIERTO', 5);
-- 6
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Arte y Cultura', DATE '2025-06-01', DATE '2025-06-28', 'ABIERTO', 6);
-- 7
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Liderazgo Comunitario', DATE '2025-07-01', DATE '2025-07-28', 'ABIERTO', 7);
-- 8
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Innovacion Tecnologica', DATE '2025-08-01', DATE '2025-08-28', 'ABIERTO', 8);
-- 9
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Desarrollo Rural', DATE '2025-09-01', DATE '2025-09-28', 'ABIERTO', 9);
-- 10
INSERT INTO CONVOCATORIA (NOMBRE, FECHA_INICIO, FECHA_FINALIZACION, ESTADO, ID_INSTITUCION) 
VALUES ('Beca Idiomas Extranjeros', DATE '2025-10-01', DATE '2025-10-28', 'ABIERTO', 10);

SELECT * FROM CONVOCATORIA;

-- Datos de la Solicitud de Becas
-- 1
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (1, 5, 'PENDIENTE', 'Guatemala');
-- 2
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (3, 6, 'EN_REVISION', 'Sacatepequez');
-- 3
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (4, 7, 'APROBADA', 'Quetzaltenango');
-- 4
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (5, 8, 'RECHAZADA', 'Chimaltenango');
-- 5
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (7, 9, 'PENDIENTE', 'Escuintla');
-- 6
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (8, 10, 'EN_REVISION', 'Alta Verapaz');
-- 7
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (9, 11, 'APROBADA', 'Solola');
-- 8
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (11, 12, 'RECHAZADA', 'Huehuetenango');
-- 9
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO)
VALUES (12, 13, 'PENDIENTE', 'San Marcos');
-- 10
INSERT INTO SOLICITUD_BECAS (ID_ESTUDAINTE, ID_CONVOCATORIA, ESTADO_SOLICITUD, DEPARTAMENTO) 
VALUES (13, 14, 'EN_REVISION', 'Retalhuleu');

SELECT * FROM SOLICITUD_BECAS;

-- Datos para Comite
-- 1
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Evaluacion Academica');
-- 2
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Becas Generales');
-- 3
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite Tecnico Cientifico');
-- 4
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Etica y Transparencia');
-- 5
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Seleccion Docente');
-- 6
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Investigacion');
-- 7
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Desarrollo Estudiantil');
-- 8
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Innovacion Educativa');
-- 9
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Calidad Academica');
-- 10
INSERT INTO COMITE (NOMBRE_COMITE) VALUES ('Comite de Asuntos Estudiantiles');

SELECT * FROM COMITE;

-- Datos de miembro de comite
-- 1
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (1, 1, 'S', 'ACTIVO');
-- 2
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (2, 4, 'S', 'ACTIVO');
-- 3
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (3, 5, 'S', 'ACTIVO');
-- 4
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (4, 6, 'S', 'ACTIVO');
-- 5
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (5, 7, 'S', 'ACTIVO');
-- 6
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (6, 8, 'S', 'ACTIVO');
-- 7
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (7, 9, 'S', 'ACTIVO');
-- 8
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (8, 10, 'S', 'ACTIVO');
-- 9
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (9, 11, 'S', 'ACTIVO');
-- 10
INSERT INTO MIEMBRO_COMITE (ID_COMITE, ID_DOCENTE, ES_EVALUADOR, ESTADO_AUTORIZACION) VALUES (10, 12, 'S', 'ACTIVO');

SELECT * FROM MIEMBRO_COMITE;

-- Datos para Evaluaión 
-- 1
-- EVALUACION (20 registros)
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (1, 1, DATE '2025-01-01', 1, 0, 'PENDIENTE');
-- 2
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (2, 4, DATE '2025-02-02', 5, 60, 'COMPLETADA');
-- 3
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (3, 5, DATE '2025-02-03', 6, 92, 'COMPLETADA');
-- 4
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (4, 6, DATE '2025-02-04', 7, 45, 'COMPLETADA');
-- 5
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (5, 7, DATE '2025-02-05', 8, 70, 'COMPLETADA');
-- 6
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (6, 8, DATE '2025-02-06', 9, 30, 'EN_PROCESO');
-- 7
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (7, 9, DATE '2025-02-07', 10, 78, 'EN_PROCESO');
-- 8
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (8, 10, DATE '2025-02-08', 11, 55, 'EN_PROCESO');
-- 9
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (9, 11, DATE '2025-02-09', 12, 0, 'PENDIENTE');
-- 10
INSERT INTO EVALUACION (ID_COMITE, ID_DOCENTE, FECHA, ID_SOLICITUD, CALIFICACION, ESTADO) 
VALUES (10, 12, DATE '2025-02-10', 13, 0, 'PENDIENTE');

-- Datos de Documento
-- 1
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (1, 'DPI', 'PDF', 100000, 'https://docs.becas.gt/doc1.pdf', 1, 1);
-- 2
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (4, 'DPI', 'PDF', 100000, 'https://docs.becas.gt/doc1.pdf', 4, 1);
-- 3
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (5, 'Certificado de Notas', 'JPG', 110000, 'https://docs.becas.gt/doc2.pdf', 21, 4);
-- 4
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (6, 'Carta de Recomendacion', 'PNG', 120000, 'https://docs.becas.gt/doc3.pdf', 22, 5);
-- 5
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (7, 'Constancia de Estudios', 'DOCX', 130000, 'https://docs.becas.gt/doc4.pdf', 23, 6);
-- 6
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (8, 'Comprobante de Ingresos', 'PDF', 140000, 'https://docs.becas.gt/doc5.pdf', 24, 7);
-- 7
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (9, 'DPI', 'JPG', 150000, 'https://docs.becas.gt/doc6.pdf', 25, 8);
-- 8
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (10, 'Certificado de Notas', 'PNG', 160000, 'https://docs.becas.gt/doc7.pdf', 26, 9);
-- 9
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (11, 'Carta de Recomendacion', 'DOCX', 170000, 'https://docs.becas.gt/doc8.pdf', 27, 10);
-- 10
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (12, 'Constancia de Estudios', 'PDF', 180000, 'https://docs.becas.gt/doc9.pdf', 28, 11);
-- 11
INSERT INTO DOCUMENTO (ID_SOLICITUD, TIPO, FORMATO, TAMANO, ENLACE, ID_USUARIO, ID_DOCENTE) 
VALUES (13, 'Comprobante de Ingresos', 'JPG', 190000, 'https://docs.becas.gt/doc10.pdf', 29, 12);

SELECT * FROM DOCUMENTO;

-- Datos para historial de estado
-- 1
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (4, 'PENDIENTE', 'EN_REVISION');
-- 2
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (5, 'EN_REVISION', 'APROBADA');
-- 3
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (6, 'EN_REVISION', 'RECHAZADA');
-- 4
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (7, 'PENDIENTE', 'RECHAZADA');
-- 5
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (8, 'PENDIENTE', 'EN_REVISION');
-- 6
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (9, 'EN_REVISION', 'APROBADA');
-- 7
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (10, 'EN_REVISION', 'RECHAZADA');
-- 8
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (11, 'PENDIENTE', 'RECHAZADA');
-- 9
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (12, 'PENDIENTE', 'EN_REVISION');
-- 10
INSERT INTO HISTORIAL_ESTADO (ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO) VALUES (13, 'EN_REVISION', 'APROBADA');

SELECT * FROM HISTORIAL_ESTADO;

COMMIT;

-- Se utilizo esta expresion debido que la enumaeracion de estudiante no seguia 1, 2, 3 y asi susesivamente 
-- afecta a las columnas con GENERATED ALWAYS AS IDENTITY, cuando un INSERT fallaba antes de insertar con éxito, ese número de ID se “perdía” igual
SELECT ID_USUARIO, NOMBRE FROM USUARIO ORDER BY ID_USUARIO;
-- Las que fueron afectadas y se modifico para la insercion de datos es;
/* 1. CONVOCATORIA
Los IDs no iniciaron en 1, sino en 5 (del 5 al 14). Los números 1-4 se perdieron por intentos fallidos previos de INSERT (relacionados con el error de la FK a INSTITUCION).
2. ESTUDIANTE
Quedó con huecos: 1, 3, 4, 5, 7, 8, 9, 11, 12, 13 (faltan el 2, 6 y 10). Se perdieron por los INSERT de prueba que fallaban intencionalmente (como el de 'Juan123' que viola la restricción de nombre).
3. DOCENTE
Quedó con huecos: 1, 4, 5, 6, 7, 8, 9, 10, 11, 12 (faltan el 2 y 3). También por inserts de prueba fallidos (como 'Maria123').
4. USUARIO
El hueco más grande: 4, 21, 22, 23, 24, 25, 26, 27, 28, 29. Hubo muchos intentos fallidos antes de que empezaran a insertarse con éxito.
5. SOLICITUD_BECAS
Consecuencia directa de los IDs reales de CONVOCATORIA y ESTUDIANTE: quedó en 4 al 13.
6. COMITE
No tuvo problema, los IDs salieron limpios del 1 al 10 (ningún INSERT falló antes).
7. MIEMBRO_COMITE
No aplica, porque su llave primaria es compuesta (ID_COMITE + ID_DOCENTE tomados de tablas ya existentes), no usa IDENTITY propio.
8. EVALUACION
Quedó con un hueco leve: faltó el 2 (secuencia 1, 3, 4, 5...). */