-- Sitema de Becas Correguido

-- Tabla Estudainte
CREATE TABLE ESTUDIANTE (
    ID_ESTUDAINTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL, 
    APELLIDO VARCHAR2(50) NOT NULL,
    DPI VARCHAR2(100) UNIQUE NOT NULL,
    CORRREO VARCHAR(100) UNIQUE NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    NIVEL_EDUCATIVO VARCHAR2(20) NOT NULL,
    /* Restricciones que se pueen aplicar dentro de la tabla 
    Se aplian en nombre, apellido y nivel educativo*/
    CONSTRAINT CK_EST_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
        
    CONSTRAINT CK_EST_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO, '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
        
    CONSTRAINT CK_EST_NIVEL
        CHECK (UPPER(NIVEL_EDUCATIVO) IN ('MEDIO','UNIVERSIDAD','POSGRADO'))
);

ALTER TABLE ESTUDIANTE
ADD CONSTRAINT CK_EST_DPI 
    CHECK (REGEXP_LIKE(DPI,'[0-9]{13}$'));

-- TABLA DOCENTE
CREATE TABLE DOCENTE (
    ID_DOCENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    NIVEL_EDUCACION VARCHAR2(20) NOT NULL,
 
    CONSTRAINT CK_DOC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_DOC_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_DOC_NIVEL
        CHECK (UPPER(NIVEL_EDUCACION) IN ('MEDIO', 'UNIVERSITARIO', 'POSGRADO'))
);

ALTER TABLE DOCENTE
ADD CONSTRAINT CK_DOC_CORREO
    CHECK(REGEXP_LIKE(CORREO,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'));
    
SELECT * FROM DOCENTE;

-- TABLA USUARIO 
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    /*Restricciones que pueden estar dentro de la tabla que es nombre*/ 
    CONSTRAINT CK_USU_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

/*Restricciones que se realizan dentro de un trigger*/
CREATE OR REPLACE TRIGGER trg_valida_pasword_usuario
BEFORE INSERT OR UPDATE OF Contrasena ON USUARIO
FOR EACH ROW
DECLARE
    v_Contrasena VARCHAR2(100);
BEGIN
    v_Contrasena := :NEW.Contrasena;
 
    IF LENGTH(v_Contrasena) < 8 OR LENGTH(v_Contrasena) > 18 THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener entre 8 y 18 caracteres');
    END IF;
 
    IF NOT REGEXP_LIKE(v_Contrasena, '[A-Z]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos una letra mayuscula');
    END IF;
 
    IF NOT REGEXP_LIKE(v_Contrasena, '[a-z]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos una letra minuscula');
    END IF;
 
    IF NOT REGEXP_LIKE(v_Contrasena, '[0-9]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos un numero');
    END IF;
 
    IF NOT REGEXP_LIKE(v_Contrasena, '[!@#$%^&*()_+\-=\[\]{};'':"\\|,.<>\/?]') THEN
        RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos un caracter especial');
    END IF;
END;  

SELECT * FROM USUARIO;

-- Tabla Universidad
CREATE TABLE UNIVERSIDAD (
    ID_UNIVERSIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
    /*Restricciones que pueden esatr dentro de la tabla en este caso es nombre*/ 
    CONSTRAINT CK_UNI_NOMBRE
        CHECK(REGEXP_LIKE(NOMBRE, '^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

ALTER TABLE UNIVERSIDAD
ADD CONSTRAINT CK_UNI_DIRECCION
    CHECK (LENGTH(TRIM(DIRECCION)) >= 10);
    
SELECT * FROM UNIVERSIDAD;

-- Tabla escuela
CREATE TABLE ESCUELA (
    ID_ESCUELA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,
 
    CONSTRAINT CK_ESC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
    
    CONSTRAINT CK_ESC_DIRECCION
        CHECK (LENGTH(TRIM(DIRECCION)) >= 10)
);

SELECT * FROM ESCUELA;

-- Tabla isntitución
CREATE TABLE INSTITUCION (
    ID_INSTITUCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UNIVERSIDAD NUMBER,
    ID_ESCUELA NUMBER,
 
    CONSTRAINT FK_INST_UNIVERSIDAD
        FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD(ID_UNIVERSIDAD),
 
    CONSTRAINT FK_INST_ESCUELA
        FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA),
 
    CONSTRAINT CK_INST_TIPO
        CHECK (
            (ID_UNIVERSIDAD IS NOT NULL AND ID_ESCUELA IS NULL)
            OR
            (ID_UNIVERSIDAD IS NULL AND ID_ESCUELA IS NOT NULL)
        )
);

SELECT * FROM INSTITUCION;

-- Tabla convocatoria
CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FINALIZACION DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    ID_INSTITUCION NUMBER,
 
    CONSTRAINT FK_CONV_INSTITUCION
        FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
 
    CONSTRAINT CK_CONV_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),
 
    CONSTRAINT CK_CONV_FECHAS
        CHECK (FECHA_FINALIZACION >= FECHA_INICIO),
 
    CONSTRAINT CK_CONV_ESTADO
        CHECK (UPPER(ESTADO) IN ('ABIERTO', 'CERRADO', 'CANCELADO'))
);

SELECT * FROM CONVOCATORIA;

-- Tabla de solicitud de becas
CREATE TABLE SOLICITUD_BECAS (
    ID_SOLICITUD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ESTUDAINTE NUMBER NOT NULL,
    ID_CONVOCATORIA NUMBER NOT NULL,
    ESTADO_SOLICITUD VARCHAR2(20) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,
 
    CONSTRAINT FK_SOL_ESTUDIANTE
        FOREIGN KEY (ID_ESTUDAINTE) REFERENCES ESTUDIANTE(ID_ESTUDAINTE),
 
    CONSTRAINT FK_SOL_CONVOCATORIA
        FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA(ID_CONVOCATORIA),
 
    CONSTRAINT CK_SOL_ESTADO
        CHECK (UPPER(ESTADO_SOLICITUD) IN ('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA')),
 
    CONSTRAINT UQ_SOL_EST_CONV
        UNIQUE (ID_ESTUDAINTE, ID_CONVOCATORIA)
);

/*Restricciones que se realiza con trigger*/
CREATE OR REPLACE TRIGGER trg_valida_estado_convocatoria_becas
BEFORE INSERT ON SOLICITUD_BECAS
FOR EACH ROW
DECLARE
    v_estado CONVOCATORIA.ESTADO%TYPE;
BEGIN
    SELECT estado
      INTO v_estado
      FROM CONVOCATORIA
     WHERE id_convocatoria = :NEW.id_convocatoria;
 
    IF UPPER(v_estado) IN ('CERRADO', 'CANCELADO') THEN
        RAISE_APPLICATION_ERROR(
            -20020,
            'No se puede ingresar la solicitud. La convocatoria está ' || v_estado || '.'
        );
    END IF;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20021,
            'La convocatoria asociada (ID: ' || :NEW.id_convocatoria || ') no existe.'
        );
END;

SELECT * FROM SOLICITUD_BECAS;

-- Tabla Comite
CREATE TABLE COMITE (
    ID_COMITE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_COMITE VARCHAR2(50) NOT NULL,
    
    CONSTRAINT CK_COM_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE_COMITE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);

SELECT * FROM COMITE;

-- Tabla miembros del comite
CREATE TABLE MIEMBRO_COMITE (
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    ES_EVALUADOR CHAR(1) DEFAULT 'N' NOT NULL,
    ESTADO_AUTORIZACION VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
 
    CONSTRAINT PK_MIEMBRO_COMITE
        PRIMARY KEY (ID_COMITE, ID_DOCENTE),
 
    CONSTRAINT FK_MIEMBRO_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),
 
    CONSTRAINT FK_MIEMBRO_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
 
    CONSTRAINT CK_MIEMBRO_ES_EVALUADOR
        CHECK (ES_EVALUADOR IN ('S','N')),
 
    CONSTRAINT CK_MIEMBRO_ESTADO_AUT
        CHECK (UPPER(ESTADO_AUTORIZACION) IN ('AUTORIZADO','ACTIVO','INACTIVO'))
);

/*Restricciones de la tabla miembros del comite que se hace por medio de un triger*/
CREATE OR REPLACE TRIGGER trg_valida_miembro_autorizado
BEFORE INSERT OR UPDATE ON MIEMBRO_COMITE
FOR EACH ROW
BEGIN
    IF UPPER(:NEW.estado_autorizacion) NOT IN ('AUTORIZADO', 'ACTIVO')
       OR :NEW.es_evaluador = 'N' THEN
 
        RAISE_APPLICATION_ERROR(
            -20030,
            'Acceso denegado: El docente (ID: ' || :NEW.id_docente || ') no está autorizado para realizar evaluaciones.'
        );
 
    END IF;
END;

SELECT * FROM MIEMBRO_COMITE;

-- Tabla Evaluación
CREATE TABLE EVALUACION (
    ID_EVALUACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    ID_SOLICITUD NUMBER NOT NULL,
    CALIFICACION NUMBER NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    RESULTADO VARCHAR2(20),
 
    CONSTRAINT FK_EVAL_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),
 
    CONSTRAINT FK_EVAL_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
 
    CONSTRAINT FK_EVAL_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
 
    CONSTRAINT UQ_EVAL_COMITE_DOC_SOL
        UNIQUE (ID_COMITE, ID_DOCENTE, ID_SOLICITUD),
        
    CONSTRAINT chk_rango_calificacion
        CHECK (calificacion BETWEEN 0 AND 100),
    
    CONSTRAINT CK_EVAL_ESTADO
    CHECK (UPPER(ESTADO) IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADA'))
);

/* Restricciones que se implementan por medio de un trigger para la tabla evaluacion*/
CREATE OR REPLACE TRIGGER trg_valida_evaluador_autorizado
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
DECLARE
    v_autorizado VARCHAR2(2);
BEGIN
    SELECT es_evaluador
      INTO v_autorizado
      FROM MIEMBRO_COMITE
     WHERE id_comite = :NEW.id_comite
       AND id_docente = :NEW.id_docente;
 
    IF v_autorizado <> 'S' THEN
        RAISE_APPLICATION_ERROR(
            -20031,
            'El miembro del comité seleccionado no tiene permisos de evaluador autorizado.'
        );
    END IF;
 
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(
            -20032,
            'El docente especificado no pertenece a este comité.'
        );
END;

CREATE OR REPLACE TRIGGER trg_gestion_evaluacion_beca
BEFORE INSERT OR UPDATE ON EVALUACION
FOR EACH ROW
BEGIN
    -- 1. Bloquear cambios si la evaluación ya estaba completada
    IF UPDATING AND UPPER(:OLD.estado) = 'COMPLETADA' THEN
        RAISE_APPLICATION_ERROR(
            -20050,
            'No se puede modificar una evaluación que ya ha sido finalizada.'
        );
    END IF;
 
    -- 2. Calcular el resultado (APROBADA/RECHAZADA) según la calificación ingresada
    IF :NEW.calificacion IS NOT NULL THEN
        IF :NEW.calificacion >= 70 THEN
            :NEW.resultado := 'APROBADA';
        ELSE
            :NEW.resultado := 'RECHAZADA';
        END IF;
    END IF;
END;

SELECT * FROM EVALUACION;

-- Tabla Documento

CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    FORMATO VARCHAR2(50) NOT NULL,
    TAMANO NUMBER NOT NULL,
    ARCHIVO BLOB,
    ENLACE VARCHAR2(500),
    FECHA_CARGA DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_DOCENTE NUMBER,
 
    CONSTRAINT FK_DOC_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
 
    CONSTRAINT FK_DOC_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
 
    CONSTRAINT FK_DOC_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),
        
    CONSTRAINT CK_DOC_TAMANO
        CHECK (TAMANO > 0 AND TAMANO <= 5242880)  -- 5 Megabytes
);
 
SELECT * FROM DOCUMENTO;

-- Tabla de historial de estado
CREATE TABLE HISTORIAL_ESTADO (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    FECHA_CAMBIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(50) NOT NULL,
    ESTADO_NUEVO VARCHAR2(50) NOT NULL,
 
    CONSTRAINT FK_HIST_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),
        
    CONSTRAINT CK_HIST_ESTADO_ANT
        CHECK (UPPER(ESTADO_ANTERIOR) IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA')),
        
    CONSTRAINT CK_HIST_ESTADO_NUE
        CHECK (UPPER(ESTADO_NUEVO) IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA')),
    
    CONSTRAINT CK_HIST_ESTADO_DIF
        CHECK (UPPER(ESTADO_ANTERIOR) <> UPPER(ESTADO_NUEVO))
);
 
/*Restriccion de trigger para la tabla historial de estado que nos permite registrar cualuier cambio en el estado de una solicitud de beca*/
CREATE OR REPLACE TRIGGER TRG_AUDITA_ESTADO_SOLICITUD
AFTER UPDATE OF ESTADO_SOLICITUD ON SOLICITUD_BECAS
FOR EACH ROW
BEGIN
    IF :OLD.ESTADO_SOLICITUD <> :NEW.ESTADO_SOLICITUD THEN
        INSERT INTO HISTORIAL_ESTADO (
            ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO, FECHA_CAMBIO
        ) VALUES (
            :OLD.ID_SOLICITUD, :OLD.ESTADO_SOLICITUD, :NEW.ESTADO_SOLICITUD, SYSDATE
        );
    END IF;
END;

SELECT * FROM HISTORIAL_ESTADO;
