-- TABLA ESTUDIANTE
CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    DPI VARCHAR2(13) UNIQUE NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    NIVEL_EDUCATIVO VARCHAR2(20) NOT NULL,

    CONSTRAINT CK_EST_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),

    CONSTRAINT CK_EST_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),

    CONSTRAINT CK_EST_NIVEL
        CHECK (UPPER(NIVEL_EDUCATIVO) IN ('MEDIO', 'UNIVERSITARIO', 'POSGRADO'))
);

/*LAS RESTRICCIONES QUE FALTARON PERO AGREGO PARA LA TABLA ESTUDIANTE SON;
1. VALIDAR QUE DPI TENGA EXACTAMENTE 13 DÍGITOS*/
ALTER TABLE ESTUDIANTE
ADD CONSTRAINT CK_EST_DPI
CHECK (REGEXP_LIKE(DPI, '^[0-9]{13}$'));

-- Tabla DOCENTE
CREATE TABLE DOCENTE (
    ID_DOCENTE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR2(50) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,
    NIVEL_EDUCACION VARCHAR2(20) NOT NULL,

    CONSTRAINT CK_DOC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),

    CONSTRAINT CK_DOC_APELLIDO
        CHECK (REGEXP_LIKE(APELLIDO,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),

    CONSTRAINT CK_DOC_NIVEL
        CHECK (UPPER(NIVEL_EDUCACION) IN ('MEDIO', 'UNIVERSITARIO', 'POSGRADO'))
);
/*LAS RESTRICCIONES QUE FALTARON PERO AGREGO A LA TABLA DOCENTE SON;
1. EL CORREO TENGA FORMATO VÁLIDO*/
ALTER TABLE DOCENTE
ADD CONSTRAINT CK_DOC_CORREO
CHECK (REGEXP_LIKE(CORREO, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'));

-- TABLA USUARIO
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(100) NOT NULL,
    CORREO VARCHAR2(100) UNIQUE NOT NULL,

    CONSTRAINT CK_USU_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);
/* LAS RESTRICCIONES QUE FALTARON PERO AGREGO EN LA TABLA USUARIO SON;
1. DEFINICION REGLAS EXACTAS PARA LA CONTRASEÑA.
1.1. LONGITUD MÍNIMA. (8 CARACTERES)
1.2. LONGITUD MÁXIMA. (18 CARACTERES)
1.3. PERMITIR EL USO DE MAYÚSCULAS.
1.4. PERMITIR EL USO DE MINÚSCULAS.
1.5. PERMITIR EL USO DE NÚMEROS.
1.6. PERMITIR CARACTERES ESPECIALES.*/

-- TABLA UNIVERSIDAD
CREATE TABLE UNIVERSIDAD (
    ID_UNIVERSIDAD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,

    CONSTRAINT CK_UNI_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA UNIVERSIDAD SON;
1. VALIDAR QUE LA DIRECCION NO ESTÉ VACÍA DE FORMA LÓGICA*/
ALTER TABLE UNIVERSIDAD
ADD CONSTRAINT CK_UNI_DIRECCION               -- TRIM ELIMINA LAS ENTRADA DE SOLO ESPACIOS 
    CHECK (LENGTH(TRIM(DIRECCION)) >= 10);    -- LENGHT EXIGUE QUE TRAS QUITAR ESPACIOS TENGA AL MENOS 10 CARACTERES 
    
-- TABLA ESCUELA
CREATE TABLE ESCUELA (
    ID_ESCUELA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) UNIQUE NOT NULL,
    DIRECCION VARCHAR2(100) NOT NULL,

    CONSTRAINT CK_ESC_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA ESCUELA SON;
1. VALIDAR QUE LA DIRECCION NO ESTÉ VACÍA DE FORMA LÓGICA*/
ALTER TABLE ESCUELA
ADD CONSTRAINT CK_ESC_DIRECCION               
    CHECK (LENGTH(TRIM(DIRECCION)) >= 10);
    
-- TABLA INSTITUCION
CREATE TABLE INSTITUCION (
    ID_INSTITUCION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_UNIVERSIDAD NUMBER,
    ID_ESCUELA NUMBER,

    CONSTRAINT FK_INST_UNIVERSIDAD
        FOREIGN KEY (ID_UNIVERSIDAD) REFERENCES UNIVERSIDAD(ID_UNIVERSIDAD),

    CONSTRAINT FK_INST_ESCUELA
        FOREIGN KEY (ID_ESCUELA) REFERENCES ESCUELA(ID_ESCUELA),

    CONSTRAINT CK_INST_TIPO
        CHECK (
            (ID_UNIVERSIDAD IS NOT NULL AND ID_ESCUELA IS NULL)
            OR
            (ID_UNIVERSIDAD IS NULL AND ID_ESCUELA IS NOT NULL)
        )
);
-- TABLA CONVOCATORIA
CREATE TABLE CONVOCATORIA (
    ID_CONVOCATORIA NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FINALIZACION DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    ID_INSTITUCION NUMBER,

    CONSTRAINT FK_CONV_INSTITUCION
        FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),

    CONSTRAINT CK_CONV_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$')),

    CONSTRAINT CK_CONV_FECHAS
        CHECK (FECHA_FINALIZACION >= FECHA_INICIO),

    CONSTRAINT CK_CONV_ESTADO
        CHECK (UPPER(ESTADO) IN ('ABIERTO', 'CERRADO', 'CANCELADO'))
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA CONVOCATORIA;
1. UNA CONVOCATORIA CERRADA O CANCELADA NO DEBE ACPETAR NUEVAS SOLICITUDES */
-- 2. NO PERMITIR CONVOCATORIAS ACTIVAS QUE SE TRASLAPEN PARA LA MISMA INSTITUCION. 

-- TABLA SOLICITUD DE BECAS
CREATE TABLE SOLICITUD_BECAS (
    ID_SOLICITUD NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ESTUDIANTE NUMBER NOT NULL,
    ID_CONVOCATORIA NUMBER NOT NULL,
    ESTADO_SOLICITUD VARCHAR2(20) NOT NULL,
    DEPARTAMENTO VARCHAR2(50) NOT NULL,

    CONSTRAINT FK_SOL_ESTUDIANTE
        FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTE(ID_ESTUDIANTE),

    CONSTRAINT FK_SOL_CONVOCATORIA
        FOREIGN KEY (ID_CONVOCATORIA) REFERENCES CONVOCATORIA(ID_CONVOCATORIA),

    CONSTRAINT CK_SOL_ESTADO
        CHECK (UPPER(ESTADO_SOLICITUD) IN ('PENDIENTE', 'EN_REVISION', 'APROBADA', 'RECHAZADA')),

    CONSTRAINT UQ_SOL_EST_CONV
        UNIQUE (ID_ESTUDIANTE, ID_CONVOCATORIA)
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA SOLICITUD_BECAS;
1. NO PERMITIR SOLICITUD SI LA CONVOCATORIA ESTÁ CERRADA O CANCELADA*/

-- TABLA COMITE
CREATE TABLE COMITE (
    ID_COMITE NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_COMITE VARCHAR2(50) NOT NULL,

    CONSTRAINT CK_COM_NOMBRE
        CHECK (REGEXP_LIKE(NOMBRE_COMITE,'^[A-Za-zÁÉÍÓÚáéíóúÑñ ]+$'))
);
-- TABLA MIEBROS DEL COMITE
CREATE TABLE MIEMBRO_COMITE (
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    -- Sirve para evitar el mismo docente sea agregado dos veces al mismo tiempo 
    CONSTRAINT PK_MIEMBRO_COMITE
        PRIMARY KEY (ID_COMITE, ID_DOCENTE),

    CONSTRAINT FK_MIEMBRO_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),

    CONSTRAINT FK_MIEMBRO_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE)
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA MIEMBRO_COMITE;
1. SOLO LOS MIEMBROS AUTORIZADOS PUEDAN EVALUAR*/
-- TABLA DOCUMENTO
CREATE TABLE DOCUMENTO (
    ID_DOCUMENTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    TIPO VARCHAR2(50) NOT NULL,
    FORMATO VARCHAR2(50) NOT NULL,
    TAMANO NUMBER NOT NULL,
    ARCHIVO BLOB,
    ENLACE VARCHAR2(500),
    FECHA_CARGA DATE DEFAULT SYSDATE NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_DOCENTE NUMBER,

    CONSTRAINT FK_DOC_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),

    CONSTRAINT FK_DOC_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),

    CONSTRAINT FK_DOC_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE)
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREO EN LA TABLA DOCUMENTO;
1. TAMAÑO MAXIMO DEL ARCHIVO*/ 
-- HAY QUE TENER EN CUNETA QUE SE TIENE ARCHIVO Y ENLACE Y SE ACPETARAN ESTAS DOS OPCIONES
ALTER TABLE DOCUMENTO
ADD CONSTRAINT CK_DOC_TAMANO                  -- EN ESTE CASO PUSE UN LIMITE DE 5MB
CHECK (TAMANO > 0 AND TAMANO <= 5242880);     -- Se puede cambiar poque aun no le e dado para que acpete este cambio
-- TABLA EVALUACION
CREATE TABLE EVALUACION (
    ID_EVALUACION NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_COMITE NUMBER NOT NULL,
    ID_DOCENTE NUMBER NOT NULL,
    FECHA DATE NOT NULL,
    ID_SOLICITUD NUMBER NOT NULL,
    CALIFICACION NUMBER NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_EVAL_COMITE
        FOREIGN KEY (ID_COMITE) REFERENCES COMITE(ID_COMITE),

    CONSTRAINT FK_EVAL_DOCENTE
        FOREIGN KEY (ID_DOCENTE) REFERENCES DOCENTE(ID_DOCENTE),

    CONSTRAINT FK_EVAL_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD),

    CONSTRAINT UQ_EVAL_COMITE_DOC_SOL
        UNIQUE (ID_COMITE, ID_DOCENTE, ID_SOLICITUD)
);
/*LAS RESTRICIONES QUE FALTARON PERO AGREGOO EN LA TABLA EVALUACION;
1. ESTABLECER UN RENGO DE CALIFICACIÓN*/
-- 2. CONTROLAR EL ESTADO (DEFINIR EL TEXTO EXACTO DE LOS ESTADOS EXACTOS DE EVALUACIÓN)
ALTER TABLE EVALUACION
ADD CONSTRAINT CK_EVAL_ESTADO
    CHECK (UPPER(ESTADO) IN ('PENDIENTE', 'EN_PROCESO', 'COMPLETADA'));
-- 3. EVALUACIÓN NO MODIFICABLE DESPUÉS DE FINALIZAR

-- TABLA HISTORIAL DE ESTADO
CREATE TABLE HISTORIAL_ESTADO (
    ID_HISTORIAL NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_SOLICITUD NUMBER NOT NULL,
    FECHA_CAMBIO TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    ESTADO_ANTERIOR VARCHAR2(50) NOT NULL,
    ESTADO_NUEVO VARCHAR2(50) NOT NULL,

    CONSTRAINT FK_HIST_SOLICITUD
        FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUD_BECAS(ID_SOLICITUD)
);
/*lAS RESTRICCIONES QUE FALTARON PERO AGREGO EN LA TABLA HISTORIAL_ESTADO
1. VALIDACION DE ESTADOS*/
ALTER TABLE HISTORIAL_ESTADO
ADD CONSTRAINT CK_HIST_ESTADO_ANT
CHECK (UPPER(ESTADO_ANTERIOR) IN ('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA'));

ALTER TABLE HISTORIAL_ESTADO
ADD CONSTRAINT CK_HIST_ESTADO_NUE
CHECK (UPPER(ESTADO_NUEVO) IN
('PENDIENTE','EN_REVISION','APROBADA','RECHAZADA'));

ALTER TABLE HISTORIAL_ESTADO
ADD CONSTRAINT CK_HIST_ESTADO_DIF
CHECK (UPPER(ESTADO_ANTERIOR) <> UPPER(ESTADO_NUEVO));




/*Prueba de insercion de datos con la tabla estudiante
En este caso sale correcto*/
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)
VALUES ('Juan', 'Perez', '9876543210101', 'juan@gmail.com', DATE '2005-05-15', 'UNIVERSITARIO');
-- En este caso es una prueba incorrecta debido que el nombre esta con numeros
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)
VALUES ('Juan123', 'Perez', '9876543210102', 'juan2@gmail.com', DATE '2005-05-15', 'UNIVERSITARIO');
SELECT * FROM ESTUDIANTE;
-- En este caso tambien es una falla porque el DPI se repite
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)
VALUES ('Pedro', 'Lopez', '9876543210101', 'pedro@gmail.com', DATE '2004-03-10', 'UNIVERSITARIO');
-- En este caso es incorrecto debido que el nivel educativo es incorrecto
INSERT INTO ESTUDIANTE (NOMBRE, APELLIDO, DPI, CORREO, FECHA_NACIMIENTO, NIVEL_EDUCATIVO)
VALUES ('Pedro', 'Lopez', '9876543210103', 'pedro@gmail.com', DATE '2004-03-10', 'PRIMARIA');

/*Prueba de insercion de datos con la tabla docente
En este caso sale correscto*/
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION)
VALUES ('Maria', 'Lopez', 'maria@gmail.com', 'POSGRADO');
SELECT * FROM DOCENTE;
-- En este caso da incorrecto por que no se cumple las norma en el nombre
INSERT INTO DOCENTE (NOMBRE, APELLIDO, CORREO, NIVEL_EDUCACION)
VALUES ('Maria123', 'Lopez', 'maria2@gmail.com', 'POSGRADO');
/*Prueba de insercion de datos con la tabla usuario
En este caso da correcto*/
INSERT INTO USUARIO (NOMBRE, CONTRASENA, CORREO)
VALUES ('Administrador', 'Clave123', 'admin@gmail.com');
SELECT * FROM USUARIO;
/*Prueba de insercion de datos con la tabla universidad
En este caso es correcto*/
INSERT INTO UNIVERSIDAD (NOMBRE, DIRECCION)
VALUES ('Universidad Central', 'Zona 10, Ciudad');
SELECT * FROM UNIVERSIDAD;
/*Prueba de inserecion de datos con la tabla escuela 
En este caso sale correcto*/
INSERT INTO ESCUELA (NOMBRE, DIRECCION)
VALUES ('Escuela Tecnica Nacional', 'Zona 1, Ciudad');
SELECT * FROM ESCUELA;
/*Prueba de nsercion de datos con la tabla institucion
En este caso es correcto pero vamos con datos de universidad*/
INSERT INTO INSTITUCION (ID_UNIVERSIDAD)
VALUES (1);
-- En este caso es correcto pero vamos con datos de escuela
INSERT INTO INSTITUCION (ID_ESCUELA)
VALUES (1);
-- En este caso da incorrecto porque van ambos IDS
INSERT INTO INSTITUCION (ID_UNIVERSIDAD, ID_ESCUELA)
VALUES (1, 1);
-- En este caso da error poque no hay datos
INSERT INTO INSTITUCION
VALUES (DEFAULT, NULL, NULL);
SELECT * FROM INSTITUCION;


SELECT USER FROM DUAL;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT CREATE TRIGGER TO Proyecto;
GRANT CREATE ANY TRIGGER TO Proyecto;
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') AS PDB_ACTUAL FROM DUAL;
-- Salio PDB_ACTUAL : 1. CDB$ROOT
SELECT USERNAME FROM ALL_USERS WHERE UPPER(USERNAME) LIKE '%PROYECTO%';
-- sALIO SOLO LA TABLA username pero no hay nada. 

-- 1. Cambiar a la Pluggable Database (ajusta XEPDB1 según el nombre de tu PDB si usas Oracle XE)
ALTER SESSION SET CONTAINER = XEPDB1; 

-- 2. Permitir modificación de scripts
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 3. Otorgar los permisos a tu usuario
GRANT CREATE TRIGGER, CREATE ANY TRIGGER TO Proyecto;

SELECT NAME, OPEN_MODE FROM V$PDBS;
ALTER SESSION SET CONTAINER = XEPDB1;
SELECT USERNAME FROM ALL_USERS WHERE UPPER(USERNAME) LIKE '%PROYECTO%';
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
GRANT CREATE TRIGGER, CREATE ANY TRIGGER TO "Proyecto";
SELECT NAME, OPEN_MODE FROM V$PDBS;
-- Salio XEPDB1 (OPEN MODE READ WRITE)
ALTER SESSION SET CONTAINER = XEPDB1;
SELECT USERNAME FROM ALL_USERS WHERE UPPER(USERNAME) LIKE '%PROYECTO%';


-- 1. Te cambias a la PDB donde realmente existen tus tablas
ALTER SESSION SET CONTAINER = XEPDB1;

-- 2. Habilitas la ejecución de scripts locales
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 3. Le das los permisos de Trigger a tu usuario
GRANT CREATE TRIGGER, CREATE ANY TRIGGER TO Proyecto;

CREATE OR REPLACE TRIGGER TRG_AUDITA_ESTADO_SOLICITUD
AFTER UPDATE OF ESTADO_SOLICITUD ON SOLICITUD_BECAS
FOR EACH ROW
BEGIN
    IF :OLD.ESTADO_SOLICITUD <> :NEW.ESTADO_SOLICITUD THEN
        INSERT INTO HISTORIAL_ESTADO (
            ID_SOLICITUD, ESTADO_ANTERIOR, ESTADO_NUEVO, FECHA_CAMBIO
        ) VALUES (
            :OLD.ID_SOLICITUD, :OLD.ESTADO_SOLICITUD, :NEW.ESTADO_SOLICITUD, SYSDATE
        );
    END IF;
END;